package practice_12_15_2021;

import java.util.Arrays;
import java.util.Scanner;

public class Fibonacci_Array {

    /*
    This is a very important interview question.
    Create a program that will give you the Fibonacci numbers up to the x value.

         Fibonacci is a sequence of number starting from 0, 1
         where the following numbers are the sum of the previous 2 numbers

          Note: Fibonacci numbers are read as index values,
          so the 0th Fibonacci is 0, 1st value is 1, 2nd value is 1, etc

                              Ex:
                                 Input:
                                   8
                                 Output:
                                   0, 1, 1, 2, 3, 5, 8, 13, 21

                                   index     Values
                                   0           0
                                   1           1
                                   2           1  index 0 + index1
                                   3           2  index 1 + index2
                                   4           3  index 2 + index3
                                   5           5


     */
        public static void main(String[] args) {
            Scanner input = new Scanner(System.in);
            System.out.println("How many Fibonacci numbers do you want to see?");
            int number = input.nextInt();
            int [] fibo = new int[number];
            fibo [0]=0;
            fibo[1]=1;
            for (int i = 2; i < number; i++) {
                fibo[i] = fibo[i-1]+fibo[i-2];   // this will give us the previous two numbers.
            }
            System.out.println(Arrays.toString(fibo));

            /*
            Google says ....The Fibonacci numbers are generated by setting F0 = 0, F1 = 1, and then using the recursive formula
Fn = Fn-1 + Fn-2
to get the rest. Thus the sequence begins: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34,
             */





            input.close();



        }


}
